config = {
	'C': 1.0,
	'kernel': 'rbf',
	'degree': 3.0,
	'gamma': 'auto',
	'coef0': 0.0,
	'shrinking': True,
	'probability': False,
	'tol': 1.0e-3,
	'cache_size': 200,
	'class_weight': None,
	'verbose': False,
	'max_iter': -1,
	'decision_function_shape': 'ovr',
	'random_state': None,
	'rs_v0': None,
	'rs_eta': 0.5,
	'alpha1': 1,
	'alpha2': 1,
	'beta1': 1,
	'beta2': 1,
	'mixture': 0.5,
	'rs_iter_err': 4,
	'rs_iter_num': 4
}